language: java
jdk:
  - oraclejdk7
sudo: false
before_install:
  - chmod +x FoodBook/mvnw
install:
  - cd FoodBook
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -e -X
script: 
  - cd FoodBook
  - mvn clean verify
